@server = https://evac03-limaylla.onrender.com

################ Categorias: ################
###
GET {{server}}/categorias
###
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Instrumento de golpe"}
################ Instrumentos: ################
###
GET {{server}}/instrumentos
###
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "congas", "categoria": "http://localhost/api/ec3/categorias/1"}
###
GET {{server}}/instrumentos/1/categoria
###
GET {{server}}/instrumentos?sort=nombre,desc